name: Build with MSBuild (VS2022 + v120 toolset)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install VS2013 (v120) Toolset for VS2022
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_BuildTools.exe -OutFile vs_BuildTools.exe
          Start-Process -Wait -FilePath .\vs_BuildTools.exe -ArgumentList `
            "--quiet", `
            "--wait", `
            "--norestart", `
            "--nocache", `
            "--add", "Microsoft.VisualStudio.Component.VC.v120", `
            "--add", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64", `
            "--installPath", "C:\BuildTools"

      - name: Find MSBuild path
        id: msbuild
        run: |
          choco install vswhere -y
          $MSBuildPath = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          echo "MSBuildPath=$MSBuildPath" >> $env:GITHUB_ENV

      - name: Build with MSBuild
        run: |
          & "$env:MSBuildPath" "src\pf2.sln" /p:Configuration=Release /p:PlatformToolset=v120
