name: Build with Visual Studio 2013

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Visual Studio 2013 Ultimate
        run: choco install VisualStudio2013Ultimate -y

      - name: Build with MSBuild
        run: |
          "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "src\pf2.sln" /p:Configuration=Release
