name: Build with Visual Studio 2013

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Microsoft Build Tools 2013
        run: |
          choco install microsoft-build-tools --version 12.0.21005.1 -y
          refreshenv

      - name: Run createpf2.bat
        run: |
          cd src
          .\createpf2.bat

      - name: Find MSBuild path
        id: msbuild
        run: |
          choco install vswhere -y
          $MSBuildPath = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          echo "MSBuildPath=$MSBuildPath" >> $env:GITHUB_ENV

      - name: Build with MSBuild
        run: |
          & "$env:MSBuildPath" "src\pf2.sln" /p:Configuration=Release /p:PlatformToolset=v120
